Add whether a user is still a member or not to .whois output
r-anime/misato pull request #188
Opened 2022-04-13 09:07 UTC by mushroom-disaster

I added a function that checks if a user is still in the server or not. It returns a string with `Yes` or `No`. And in the case of an error it returns `N/A`

2022-04-13 18:01 UTC, eritbh requested changes

2022-04-19 11:09 UTC, mushroom-disaster commented on src/bot/commands/whois.js
> +		isMember = guild.members.get(userID) && await guild.getRESTMember(userID) ? 'Yes' : 'No';
I made the changes

2022-04-19 14:13 UTC, eritbh commented on src/bot/commands/whois.js
> + *Returns a string stating whether a user is still a member or not
```suggestion
 * Returns a string stating whether a user is still a member or not
```

2022-04-19 14:13 UTC, eritbh approved these changes
one more dumb nit, then I think you're good to merge

2022-04-19 14:23 UTC, merged